version: "3.8"

services:
  db:
    image: postgres:12.13-alpine3.17
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432

  app:
    image: openjdk:11-slim-buster
    depends_on:
      - db
    build:
      dockerfile: ./app.dockerfile
      context: .
    restart: on-failure
    ports:
      - 8080:8080
volumes:
  db:

